/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSolyRouteImport } from './routes/api/soly'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActivateCodeRouteImport } from './routes/_authenticated/activate-code'
import { Route as AuthenticatedSubjectIdRouteImport } from './routes/_authenticated/subject.$id'
import { Route as AuthenticatedDepartmentSlugRouteImport } from './routes/_authenticated/department.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSolyRoute = ApiSolyRouteImport.update({
  id: '/api/soly',
  path: '/api/soly',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivateCodeRoute =
  AuthenticatedActivateCodeRouteImport.update({
    id: '/activate-code',
    path: '/activate-code',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectIdRoute = AuthenticatedSubjectIdRouteImport.update({
  id: '/subject/$id',
  path: '/subject/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentSlugRoute =
  AuthenticatedDepartmentSlugRouteImport.update({
    id: '/department/$slug',
    path: '/department/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activate-code': typeof AuthenticatedActivateCodeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/api/soly': typeof ApiSolyRoute
  '/department/$slug': typeof AuthenticatedDepartmentSlugRoute
  '/subject/$id': typeof AuthenticatedSubjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activate-code': typeof AuthenticatedActivateCodeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/api/soly': typeof ApiSolyRoute
  '/department/$slug': typeof AuthenticatedDepartmentSlugRoute
  '/subject/$id': typeof AuthenticatedSubjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activate-code': typeof AuthenticatedActivateCodeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/api/soly': typeof ApiSolyRoute
  '/_authenticated/department/$slug': typeof AuthenticatedDepartmentSlugRoute
  '/_authenticated/subject/$id': typeof AuthenticatedSubjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activate-code'
    | '/admin'
    | '/dashboard'
    | '/super-admin'
    | '/api/soly'
    | '/department/$slug'
    | '/subject/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activate-code'
    | '/admin'
    | '/dashboard'
    | '/super-admin'
    | '/api/soly'
    | '/department/$slug'
    | '/subject/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activate-code'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/super-admin'
    | '/api/soly'
    | '/_authenticated/department/$slug'
    | '/_authenticated/subject/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiSolyRoute: typeof ApiSolyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/soly': {
      id: '/api/soly'
      path: '/api/soly'
      fullPath: '/api/soly'
      preLoaderRoute: typeof ApiSolyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activate-code': {
      id: '/_authenticated/activate-code'
      path: '/activate-code'
      fullPath: '/activate-code'
      preLoaderRoute: typeof AuthenticatedActivateCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subject/$id': {
      id: '/_authenticated/subject/$id'
      path: '/subject/$id'
      fullPath: '/subject/$id'
      preLoaderRoute: typeof AuthenticatedSubjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/department/$slug': {
      id: '/_authenticated/department/$slug'
      path: '/department/$slug'
      fullPath: '/department/$slug'
      preLoaderRoute: typeof AuthenticatedDepartmentSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivateCodeRoute: typeof AuthenticatedActivateCodeRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedDepartmentSlugRoute: typeof AuthenticatedDepartmentSlugRoute
  AuthenticatedSubjectIdRoute: typeof AuthenticatedSubjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivateCodeRoute: AuthenticatedActivateCodeRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedDepartmentSlugRoute: AuthenticatedDepartmentSlugRoute,
  AuthenticatedSubjectIdRoute: AuthenticatedSubjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiSolyRoute: ApiSolyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
